image: Visual Studio 2015

install:
- ps: (new-object net.webclient).DownloadString('https://raw.githubusercontent.com/JoeBradley/TeamRoomExtension/' + $env:APPVEYOR_REPO_BRANCH + '/BuildScript.ps1') | iex


before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts 

deploy:
  provider: Environment
  name: TeamRoom GitHub